require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/**/*"
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Rails/FilePath:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/**/*
