require: rubocop-rails

AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
